### ISSUE TITLE
Fail to import a file without `rules` section

### ISSUE THREAD

**Issue by ybiquitous** [sider/goodcheck#29]
On v1.4.0, the nice feature to import rules from another location was introduced.

- https://github.com/sider/goodcheck/blob/master/CHANGELOG.md#140-2018-10-11
- https://github.com/sider/goodcheck/releases/tag/v1.4.0
- https://github.com/sider/goodcheck/pull/26

By using this feature, I want to share `goodcheck.yml` files in other repositories.
But, now it fails to import files directly.

E.g.

```yaml
# goodcheck.yml in a repository
rules:
  - id: com.foo.rule_1
  # some rule definitions...

import:
  - https://raw.githubusercontent.com/foo/bar/master/goodcheck.yml #=> fail
  - goodcheck-extra-rules.yml #=> success
```

```yaml
# goodcheck.yml in another repository 'foo/bar'
rules:
  - id: com.foo.bar.rule_2
  # some rule definitions...
```

```yaml
# goodcheck-extra-rules.yml
- id: com.foo.extra.rule_1
# some rule definitions...
```

Can goodcheck import also file with `rules:` section?

### Environment

- goodcheck 1.4.1
- ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

### Reproduction

Run the following script in a terminal:

```sh
# Setup
mkdir goodcheck-error-sample
cd goodcheck-error-sample

# Create goodcheck.yml
goodcheck init

# Append `import` section
cat <<EOF >>goodcheck.yml
import:
  - https://raw.githubusercontent.com/sider/goodcheck/df98c71941af840eb689bbd0d5dae17ab31e3ed2/sample.yml
EOF

# Test goodcheck configuration
goodcheck test
```

Outputs the following error:

```
#<StrongJSON::Type::Error: Expected type of value {:rules=>[{:id=>"sample.typo", :pattern=>["Github", "FaceBook"], :message=>"Write GitHub and Facebook\n\nTheir names are GitHub and Facebook.\nMaybe, you are misspelling.\n", :pass=>"GitHub", :fail=>"Github"}, {:id=>"sample.debug_print", :pattern=>[{:token=>"pp"}, {:token=>"p"}], :glob=>"**/*.rb", :message=>"You should not use debug print\n", :pass=>["render \"app/views/welcome.html.erb\""], :fail=>["pp(\"Hello World\")"]}], :import=>["https://gist.githubusercontent.com/soutaro/6362c89acd7d6771ae6ebfc615be402d/raw/7f04b973c2c8df70783cd7deb955ab95d1375b2d/sample.yml"]} is array(object(id: string, pattern: enum(array(enum(object(regexp: string, case_sensitive: optional(boolean), multiline: optional(boolean)), object(literal: string, case_sensitive: optional(boolean)), object(token: string, case_sensitive: optional(boolean)), object(regexp: string, case_insensitive: optional(boolean), multiline: optional(boolean)), object(literal: string, case_insensitive: optional(boolean)), object(token: string, case_insensitive: optional(boolean)), string)), enum(object(regexp: string, case_sensitive: optional(boolean), multiline: optional(boolean)), object(literal: string, case_sensitive: optional(boolean)), object(token: string, case_sensitive: optional(boolean)), object(regexp: string, case_insensitive: optional(boolean), multiline: optional(boolean)), object(literal: string, case_insensitive: optional(boolean)), object(token: string, case_insensitive: optional(boolean)), string)), message: string, justification: optional(enum(array(string), string)), glob: optional(enum(array(enum(object(pattern: string, encoding: optional(enum(literal(ASCII-8BIT), literal(UTF-8), literal(US-ASCII), literal(UTF-16BE), literal(UTF-16LE), literal(UTF-32BE), literal(UTF-32LE), literal(UTF-16), literal(UTF-32), literal(UTF8-MAC), literal(EUC-JP), literal(Windows-31J), literal(Big5), literal(Big5-HKSCS), literal(Big5-UAO), literal(CP949), literal(Emacs-Mule), literal(EUC-KR), literal(EUC-TW), literal(GB2312), literal(GB18030), literal(GBK), literal(ISO-8859-1), literal(ISO-8859-2), literal(ISO-8859-3), literal(ISO-8859-4), literal(ISO-8859-5), literal(ISO-8859-6), literal(ISO-8859-7), literal(ISO-8859-8), literal(ISO-8859-9), literal(ISO-8859-10), literal(ISO-8859-11), literal(ISO-8859-13), literal(ISO-8859-14), literal(ISO-8859-15), literal(ISO-8859-16), literal(KOI8-R), literal(KOI8-U), literal(Shift_JIS), literal(Windows-1250), literal(Windows-1251), literal(Windows-1252), literal(Windows-1253), literal(Windows-1254), literal(Windows-1257), literal(BINARY), literal(IBM437), literal(CP437), literal(IBM737), literal(CP737), literal(IBM775), literal(CP775), literal(CP850), literal(IBM850), literal(IBM852), literal(CP852), literal(IBM855), literal(CP855), literal(IBM857), literal(CP857), literal(IBM860), literal(CP860), literal(IBM861), literal(CP861), literal(IBM862), literal(CP862), literal(IBM863), literal(CP863), literal(IBM864), literal(CP864), literal(IBM865), literal(CP865), literal(IBM866), literal(CP866), literal(IBM869), literal(CP869), literal(Windows-1258), literal(CP1258), literal(GB1988), literal(macCentEuro), literal(macCroatian), literal(macCyrillic), literal(macGreek), literal(macIceland), literal(macRoman), literal(macRomania), literal(macThai), literal(macTurkish), literal(macUkraine), literal(CP950), literal(Big5-HKSCS:2008), literal(CP951), literal(IBM037), literal(ebcdic-cp-us), literal(stateless-ISO-2022-JP), literal(eucJP), literal(eucJP-ms), literal(euc-jp-ms), literal(CP51932), literal(EUC-JIS-2004), literal(EUC-JISX0213), literal(eucKR), literal(eucTW), literal(EUC-CN), literal(eucCN), literal(GB12345), literal(CP936), literal(ISO-2022-JP), literal(ISO2022-JP), literal(ISO-2022-JP-2), literal(ISO2022-JP2), literal(CP50220), literal(CP50221), literal(ISO8859-1), literal(ISO8859-2), literal(ISO8859-3), literal(ISO8859-4), literal(ISO8859-5), literal(ISO8859-6), literal(Windows-1256), literal(CP1256), literal(ISO8859-7), literal(ISO8859-8), literal(Windows-1255), literal(CP1255), literal(ISO8859-9), literal(ISO8859-10), literal(ISO8859-11), literal(TIS-620), literal(Windows-874), literal(CP874), literal(ISO8859-13), literal(ISO8859-14), literal(ISO8859-15), literal(ISO8859-16), literal(CP878), literal(MacJapanese), literal(MacJapan), literal(ASCII), literal(ANSI_X3.4-1968), literal(646), literal(UTF-7), literal(CP65000), literal(CP65001), literal(UTF-8-MAC), literal(UTF-8-HFS), literal(UCS-2BE), literal(UCS-4BE), literal(UCS-4LE), literal(CP932), literal(csWindows31J), literal(SJIS), literal(PCK), literal(CP1250), literal(CP1251), literal(CP1252), literal(CP1253), literal(CP1254), literal(CP1257), literal(UTF8-DoCoMo), literal(SJIS-DoCoMo), literal(UTF8-KDDI), literal(SJIS-KDDI), literal(ISO-2022-JP-KDDI), literal(stateless-ISO-2022-JP-KDDI), literal(UTF8-SoftBank), literal(SJIS-SoftBank), literal(locale), literal(external), literal(filesystem), literal(internal)))), string)), object(pattern: string, encoding: optional(enum(literal(ASCII-8BIT), literal(UTF-8), literal(US-ASCII), literal(UTF-16BE), literal(UTF-16LE), literal(UTF-32BE), literal(UTF-32LE), literal(UTF-16), literal(UTF-32), literal(UTF8-MAC), literal(EUC-JP), literal(Windows-31J), literal(Big5), literal(Big5-HKSCS), literal(Big5-UAO), literal(CP949), literal(Emacs-Mule), literal(EUC-KR), literal(EUC-TW), literal(GB2312), literal(GB18030), literal(GBK), literal(ISO-8859-1), literal(ISO-8859-2), literal(ISO-8859-3), literal(ISO-8859-4), literal(ISO-8859-5), literal(ISO-8859-6), literal(ISO-8859-7), literal(ISO-8859-8), literal(ISO-8859-9), literal(ISO-8859-10), literal(ISO-8859-11), literal(ISO-8859-13), literal(ISO-8859-14), literal(ISO-8859-15), literal(ISO-8859-16), literal(KOI8-R), literal(KOI8-U), literal(Shift_JIS), literal(Windows-1250), literal(Windows-1251), literal(Windows-1252), literal(Windows-1253), literal(Windows-1254), literal(Windows-1257), literal(BINARY), literal(IBM437), literal(CP437), literal(IBM737), literal(CP737), literal(IBM775), literal(CP775), literal(CP850), literal(IBM850), literal(IBM852), literal(CP852), literal(IBM855), literal(CP855), literal(IBM857), literal(CP857), literal(IBM860), literal(CP860), literal(IBM861), literal(CP861), literal(IBM862), literal(CP862), literal(IBM863), literal(CP863), literal(IBM864), literal(CP864), literal(IBM865), literal(CP865), literal(IBM866), literal(CP866), literal(IBM869), literal(CP869), literal(Windows-1258), literal(CP1258), literal(GB1988), literal(macCentEuro), literal(macCroatian), literal(macCyrillic), literal(macGreek), literal(macIceland), literal(macRoman), literal(macRomania), literal(macThai), literal(macTurkish), literal(macUkraine), literal(CP950), literal(Big5-HKSCS:2008), literal(CP951), literal(IBM037), literal(ebcdic-cp-us), literal(stateless-ISO-2022-JP), literal(eucJP), literal(eucJP-ms), literal(euc-jp-ms), literal(CP51932), literal(EUC-JIS-2004), literal(EUC-JISX0213), literal(eucKR), literal(eucTW), literal(EUC-CN), literal(eucCN), literal(GB12345), literal(CP936), literal(ISO-2022-JP), literal(ISO2022-JP), literal(ISO-2022-JP-2), literal(ISO2022-JP2), literal(CP50220), literal(CP50221), literal(ISO8859-1), literal(ISO8859-2), literal(ISO8859-3), literal(ISO8859-4), literal(ISO8859-5), literal(ISO8859-6), literal(Windows-1256), literal(CP1256), literal(ISO8859-7), literal(ISO8859-8), literal(Windows-1255), literal(CP1255), literal(ISO8859-9), literal(ISO8859-10), literal(ISO8859-11), literal(TIS-620), literal(Windows-874), literal(CP874), literal(ISO8859-13), literal(ISO8859-14), literal(ISO8859-15), literal(ISO8859-16), literal(CP878), literal(MacJapanese), literal(MacJapan), literal(ASCII), literal(ANSI_X3.4-1968), literal(646), literal(UTF-7), literal(CP65000), literal(CP65001), literal(UTF-8-MAC), literal(UTF-8-HFS), literal(UCS-2BE), literal(UCS-4BE), literal(UCS-4LE), literal(CP932), literal(csWindows31J), literal(SJIS), literal(PCK), literal(CP1250), literal(CP1251), literal(CP1252), literal(CP1253), literal(CP1254), literal(CP1257), literal(UTF8-DoCoMo), literal(SJIS-DoCoMo), literal(UTF8-KDDI), literal(SJIS-KDDI), literal(ISO-2022-JP-KDDI), literal(stateless-ISO-2022-JP-KDDI), literal(UTF8-SoftBank), literal(SJIS-SoftBank), literal(locale), literal(external), literal(filesystem), literal(internal)))), string)), pass: optional(enum(array(string), string)), fail: optional(enum(array(string), string))))>
  /usr/local/lib/ruby/gems/2.5.0/gems/strong_json-0.7.1/lib/strong_json/type.rb:119:in `coerce'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:85:in `block (2 levels) in load_import'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/import_loader.rb:76:in `load_http'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/import_loader.rb:30:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:82:in `block in load_import'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:81:in `load_import'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:65:in `block (2 levels) in load'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:64:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:64:in `block in load'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/config_loader.rb:57:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/commands/config_loading.rb:10:in `load_config!'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/commands/test.rb:22:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/cli.rb:131:in `test'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/lib/goodcheck/cli.rb:28:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/goodcheck-1.4.1/exe/goodcheck:7:in `<top (required)>'
  /usr/local/bin/goodcheck:23:in `load'
  /usr/local/bin/goodcheck:23:in `<main>'
```

**Comment by ybiquitous** [comment]
Now I think better to support both data formats (with `rules` and without `rules`).

Because I want to make sharing `goodcheck.yml` easier.

In order to achieve it,  I think important to make less things which must remember about data formats of `goodcheck.yml`.

**Comment by toadkicker** [comment]
I've been working on an article for Goodcheck and reading through the code to understand its capabilities more. I want to propose a few ideas for this issue:

1) Use something similar to Gemfile's 'source' attribute instead of having import witthout being under a rule. That would to me be more ruby-ish and familar if I wanted to use a single source for my rules. That could be useful, and recursive, if targets also define other sources when repositories move and other maintenance events happen.

2) Require `import` belong under a `rule` parent node. This would let developers id an imported rule, and in the same configuration leaf override anything they want from that import.

**Comment by ybiquitous** [comment]
@toadkicker Thanks for your suggestion!

Surely, there may be some better ways to share rules (publish & import rules). I think current `import` implementation is very nice and widely available but a bit primitive. 😅 

Your idea seems very interesting to me but current Goodcheck doesn't have rules to be shared by developers, who are very few.

I'm trying experiment to share some rules on <https://github.com/sider/goodcheck-rules>.
I want to look what users & developers really want and feel very useful by Goodcheck... 🤔

**Comment by ybiquitous** [comment]
Now I think the current behavior of Goodcheck makes sense. So I close this issue.
